name: bilibili
on:
  workflow_dispatch:
  schedule:
    # 每天凌晨执行，UTC 时间，这里是凌晨12点
    - cron: '0 0 * * *'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: bilibili
        run: |
          # Send HTTP GET request to the API endpoint
          response=$(curl -s -o /dev/null -w "%{http_code}" https://app.bilibili.com/x/v2/space/archive/cursor?vmid=224267770)
          
          # Check response status code
          if [ $response -eq 200 ]; then
            echo "API is working fine."
          else
            echo "API may have issues. Status code: $response"
            exit 1
          fi
